# Form implementation generated from reading ui file 'applications.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 605)
        MainWindow.setMinimumSize(QtCore.QSize(820, 605))
        MainWindow.setStyleSheet("QMainWindow{\n"
" \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainFrame.setMinimumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setBold(False)
        self.mainFrame.setFont(font)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameLeft = QtWidgets.QFrame(parent=self.mainFrame)
        self.frameLeft.setMinimumSize(QtCore.QSize(250, 500))
        self.frameLeft.setStyleSheet("")
        self.frameLeft.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameLeft.setObjectName("frameLeft")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameLeft)
        self.verticalLayout_4.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameTopLeft = QtWidgets.QFrame(parent=self.frameLeft)
        self.frameTopLeft.setMinimumSize(QtCore.QSize(0, 150))
        self.frameTopLeft.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameTopLeft.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameTopLeft.setObjectName("frameTopLeft")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameTopLeft)
        self.verticalLayout_5.setContentsMargins(-1, 15, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelLogo = QtWidgets.QLabel(parent=self.frameTopLeft)
        self.labelLogo.setMinimumSize(QtCore.QSize(221, 61))
        self.labelLogo.setMaximumSize(QtCore.QSize(221, 61))
        self.labelLogo.setText("")
        self.labelLogo.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.labelLogo.setPixmap(QtGui.QPixmap("icons/logoPhoto.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout_5.addWidget(self.labelLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.pushButtonBackMainPage = QtWidgets.QPushButton(parent=self.frameTopLeft)
        self.pushButtonBackMainPage.setMinimumSize(QtCore.QSize(121, 31))
        self.pushButtonBackMainPage.setMaximumSize(QtCore.QSize(121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonBackMainPage.setFont(font)
        self.pushButtonBackMainPage.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.2em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonBackMainPage.setObjectName("pushButtonBackMainPage")
        self.verticalLayout_5.addWidget(self.pushButtonBackMainPage)
        self.verticalLayout_4.addWidget(self.frameTopLeft)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.frameMenu = QtWidgets.QFrame(parent=self.frameLeft)
        self.frameMenu.setMinimumSize(QtCore.QSize(221, 330))
        self.frameMenu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMenu.setObjectName("frameMenu")
        self.labelMentorMeetings = QtWidgets.QLabel(parent=self.frameMenu)
        self.labelMentorMeetings.setGeometry(QtCore.QRect(40, 220, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.labelMentorMeetings.setFont(font)
        self.labelMentorMeetings.setStyleSheet("color: rgb(70, 70, 70);")
        self.labelMentorMeetings.setObjectName("labelMentorMeetings")
        self.pushButtonAllApplications = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonAllApplications.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonAllApplications.setFont(font)
        self.pushButtonAllApplications.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.2em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonAllApplications.setObjectName("pushButtonAllApplications")
        self.pushButtonFilterApplications = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonFilterApplications.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonFilterApplications.setFont(font)
        self.pushButtonFilterApplications.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.2em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonFilterApplications.setObjectName("pushButtonFilterApplications")
        self.pushButtonDuplicateRegistrations = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonDuplicateRegistrations.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonDuplicateRegistrations.setFont(font)
        self.pushButtonDuplicateRegistrations.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.05em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonDuplicateRegistrations.setObjectName("pushButtonDuplicateRegistrations")
        self.pushButtonDifferentRegistrations = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonDifferentRegistrations.setGeometry(QtCore.QRect(10, 130, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonDifferentRegistrations.setFont(font)
        self.pushButtonDifferentRegistrations.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.05em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonDifferentRegistrations.setObjectName("pushButtonDifferentRegistrations")
        self.pushButtonPreviousVITControl = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonPreviousVITControl.setGeometry(QtCore.QRect(10, 170, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonPreviousVITControl.setFont(font)
        self.pushButtonPreviousVITControl.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.2em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonPreviousVITControl.setObjectName("pushButtonPreviousVITControl")
        self.pushButtonScheduled = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonScheduled.setGeometry(QtCore.QRect(10, 250, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonScheduled.setFont(font)
        self.pushButtonScheduled.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.2em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonScheduled.setObjectName("pushButtonScheduled")
        self.pushButtonUnscheduled = QtWidgets.QPushButton(parent=self.frameMenu)
        self.pushButtonUnscheduled.setGeometry(QtCore.QRect(10, 290, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonUnscheduled.setFont(font)
        self.pushButtonUnscheduled.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"letter-spacing: 0.2em;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" \n"
" background-color: rgb(90, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: white;\n"
" color: rgb(65, 77, 77);\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonUnscheduled.setObjectName("pushButtonUnscheduled")
        self.verticalLayout_4.addWidget(self.frameMenu)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.frameLeftBottom = QtWidgets.QFrame(parent=self.frameLeft)
        self.frameLeftBottom.setMinimumSize(QtCore.QSize(0, 45))
        self.frameLeftBottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameLeftBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameLeftBottom.setObjectName("frameLeftBottom")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.frameLeftBottom)
        self.pushButtonExit.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.pushButtonExit.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        font.setBold(False)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
" background-color: rgb(148, 0, 0);\n"
" color: rgb(255, 255, 255);\n"
" border-radius: 10px;\n"
" letter-spacing: 0.2em;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgba(157, 9, 19,200);\n"
"  color: rgb(255, 255, 255);\n"
"  border-radius: 10px;\n"
"  border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: white;\n"
"  color: rgb(170, 0, 0);\n"
"  border: 1px solid black;\n"
"}\n"
"\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout_4.addWidget(self.frameLeftBottom)
        self.horizontalLayout_2.addWidget(self.frameLeft)
        self.frameRight = QtWidgets.QFrame(parent=self.mainFrame)
        self.frameRight.setMinimumSize(QtCore.QSize(300, 300))
        self.frameRight.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameRight.setObjectName("frameRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameRight)
        self.verticalLayout.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frameRight)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("letter-spacing: 0.2em;\n"
"color: rgb(60, 70, 70);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frameTopRight_2 = QtWidgets.QFrame(parent=self.frameRight)
        self.frameTopRight_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frameTopRight_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frameTopRight_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameTopRight_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameTopRight_2.setObjectName("frameTopRight_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameTopRight_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.frame_6 = QtWidgets.QFrame(parent=self.frameTopRight_2)
        self.frame_6.setMinimumSize(QtCore.QSize(500, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(1300, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(50, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameSearch_2 = QtWidgets.QFrame(parent=self.frame_6)
        self.frameSearch_2.setMinimumSize(QtCore.QSize(430, 50))
        self.frameSearch_2.setMaximumSize(QtCore.QSize(665, 50))
        self.frameSearch_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameSearch_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameSearch_2.setObjectName("frameSearch_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frameSearch_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.frameSearch_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSearch.sizePolicy().hasHeightForWidth())
        self.lineEditSearch.setSizePolicy(sizePolicy)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(600, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
" background-color: white;\n"
" border-bottom-left-radius: 10px;\n"
" border-top-left-radius: 10px;\n"
" padding-left: 10px;\n"
" border: 1px solid gray;\n"
" border-right: none;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border-color: black;\n"
"}")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setClearButtonEnabled(False)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout_4.addWidget(self.lineEditSearch)
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.frameSearch_2)
        self.pushButtonSearch.setMinimumSize(QtCore.QSize(65, 35))
        self.pushButtonSearch.setMaximumSize(QtCore.QSize(65, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonSearch.setFont(font)
        self.pushButtonSearch.setStyleSheet("\n"
"\n"
"QPushButton {\n"
" background-color: rgb(80, 90, 90);\n"
" border-bottom-right-radius: 10px;\n"
" border-top-right-radius: 10px;\n"
" padding-right: 5px;\n"
" border: 1px solid rgb(50, 60, 60);\n"
" border-left:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" background-color: rgb(110, 120, 120);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: rgb(150, 160, 160);;\n"
" border: 1px solid black;\n"
"}")
        self.pushButtonSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/search_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.horizontalLayout_4.addWidget(self.pushButtonSearch)
        self.verticalLayout_6.addWidget(self.frameSearch_2)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addWidget(self.frameTopRight_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frameRight)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_2.addWidget(self.frameRight)
        self.verticalLayout_2.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBackMainPage.setText(_translate("MainWindow", "<  Main Page"))
        self.labelMentorMeetings.setText(_translate("MainWindow", "Mentor Meetings"))
        self.pushButtonAllApplications.setText(_translate("MainWindow", "All Applications"))
        self.pushButtonFilterApplications.setText(_translate("MainWindow", "Filter Applications"))
        self.pushButtonDuplicateRegistrations.setText(_translate("MainWindow", "Duplicate Registrations"))
        self.pushButtonDifferentRegistrations.setText(_translate("MainWindow", "Different Registrations"))
        self.pushButtonPreviousVITControl.setText(_translate("MainWindow", "Previous VIT Control"))
        self.pushButtonScheduled.setText(_translate("MainWindow", "Scheduled"))
        self.pushButtonUnscheduled.setText(_translate("MainWindow", "Unscheduled"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "APPLICATIONS"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
